version: '3'

services:
  boldo-web:
    stdin_open: true
    tty: true
    container_name: boldo-web
    build:
      context: ./boldo-web
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./boldo-web/src:/home/app/src
    environment:
      - REACT_APP_SOCKETS_ADDRESS=http://localhost:8000
      - REACT_APP_SERVER_ADDRESS=http://localhost:8008
    networks:
      - boldo-network-lite

  redis:
    image: redis
    container_name: redis-db
    restart: unless-stopped
    networks:
      - boldo-network-lite

  boldo-server:
    image: node:14.15.1
    volumes:
      - "./boldo-server/:/usr/src/app/"
    command: /bin/sh -c "cd /usr/src/app/ && npm i && npm run build && apt-get update && ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone && npm start -p 8008"
    container_name: boldo-server
    restart: unless-stopped
    environment:
      - SECRET=secure_server_secret
      - MONGODB_URI=
      - IHUB_ADDRESS=
      - CLIENT_ADDRESS=http://localhost:3000
      - KEYCLOAK_ADDRESS=
      - REDIS_URL=redis://redis-db:6379
      - TZ=America/Asuncion
      - PRIVATE_KEY
      - BOLDO_ADMIN=
      - BOLDO_PASS=
    ports:
      - "8008:8008"
    networks:
      - boldo-network-lite

  boldo-socket:
    build: ./boldo-sockets
    container_name: boldo-sockets
    restart: unless-stopped
    environment:
      - SECRET=secure_server_secret
      - PORT=8000
      - PUBLIC_KEY
    ports:
      - "8000:8000"

networks:
  boldo-network-lite:
    external: true